### ISSUE TITLE
development roadmap

### ISSUE THREAD

**Issue by senderle** [joelslee/spa#1]
This is a short document with a list of major features we need to add. Some of these could become their own issues, but for now I'm just creating a checklist.

- [x] Move the map to the front page.
- [x] Create a system for displaying protest data. (This comes straight from the airtables data.)
  - [x] Put the protest data in the [`_data`](https://jekyllrb.com/docs/datafiles/) folder.
  - [x] Create the layout, which should map columns in the CSV to fields on the page (maybe using a [`<dl>`](https://www.w3schools.com/tags/tag_dl.asp)). It should be possible to pass a row index from the front matter to this layout; the layout will then pull that row and map its columns to display fields.
  - [x] Create a single test page, which will be a markdown file in `_pages` using the above layout. The front matter will have a `row_index` variable, which is the value the layout uses to decide which row to display.
- [x] Create a system for displaying country data. (To be aggregated from the AirTables data; KS will send details about what this should have, but we don't need to wait; we can just create some fake test data for now.)
  - [x] Create a simple fake country data CSV and put it in the `_data` folder. 
  - [x] Create the layout, which should map columns in the fake CSV to fields on the page (maybe using a [`<dl>`](https://www.w3schools.com/tags/tag_dl.asp)). It should be possible to pass a row index from the front matter to this layout; the layout will then pull that row and map its columns to display fields.
  - [x] Create a single test page, which will be a markdown file in `_pages` using the above layout. The front matter will have a `row_index` variable, which is the value the layout uses to decide which row to display.
- [x] Create two maps based on the current one, dividing its functionality into two. One should be a choropleth with the current tileset; the other should have points displayed over a google map tileset (if possible). These two maps should be toggleable, in the style used by the fandom project. (Joel, you'll remember how to do this).
- [x] Figure out how to use CustomJS callbacks to display contextual information in a `div` on the main page (i.e. outside the vis). [This](https://docs.bokeh.org/en/latest/docs/user_guide/interaction/callbacks.html#customjs-for-selections) should provide some hints about how to proceed, though it uses another visualization; but the fact that it works suggests to me that this shouldn't be that different.

**Comment by joelsjlee** [comment]
Finished the systems and layouts for displaying protest and country data. I'm using dl tags but they don't seem to be formatting in the way we want. This theme we're using also has it so that every page we make becomes an option on the home layout top bar. Both of these issues have to do with the theme's layouts probably so i'm not concerned.

I think the google map tileset is a little more complicated, it doesn't seem like what we have currently with Bokeh and map.py will transfer easily to the Google Maps API. However, I did tabulate four of the tile_providers that Bokeh let's us use, and they don't look that bad. These new changes are on my branch.

![image](https://user-images.githubusercontent.com/34225086/87352383-f0f25b00-c528-11ea-9b45-b0e8830a70bf.png)
![image](https://user-images.githubusercontent.com/34225086/87352403-f94a9600-c528-11ea-920e-ed0a1fa05c28.png)
![image](https://user-images.githubusercontent.com/34225086/87352423-0071a400-c529-11ea-81d8-e5ef04311ac8.png)
![image](https://user-images.githubusercontent.com/34225086/87352445-08c9df00-c529-11ea-93cc-52d3ae9fbb2c.png)
