### ISSUE TITLE
development roadmap #2

### ISSUE THREAD

**Issue by joelsjlee** [joelslee/spa#2]
- [x] more readable tab names

- [x] github pages version up-to-date

- [x] I have a new version of the data; we should be using it

- [ ] python script for aggregating country data; this should generate the csv for the country pages. This should be taken from the `gadm28_countries.geojson` in `data_to_map/data`

- [ ] completing country and protest pages layouts based on spec from KS. These can be found on the wiki of this repo.

- [ ] creating an interactive filter for the point map. [This is a good place to start](https://discourse.bokeh.org/t/how-to-trigger-customjs-on-data-change/4271/13). And here's a relevant slack picture
![image](https://user-images.githubusercontent.com/34225086/88077252-0ed34780-cb49-11ea-92ed-2dd4ed01c115.png)

- [x] separating out the heat map and dot map. This should probably be tabulated (?)
